# Generated by Django 3.2.10 on 2022-05-23 12:52

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostReadCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_url_name', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_type', models.CharField(max_length=55)),
                ('post_category', models.CharField(max_length=55)),
                ('post_status', models.CharField(max_length=55)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(blank=True, max_length=80, null=True)),
                ('media_type', models.CharField(blank=True, max_length=20, null=True)),
                ('media_status', models.CharField(max_length=20)),
                ('media_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_category', models.TextField(max_length=40)),
                ('media_file', models.ImageField(upload_to=blog.models.where_to_save_media)),
                ('media_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
    ]
