# Generated by Django 3.2.10 on 2022-05-23 12:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreadcounter',
            name='posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='postreadcounter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
