# Generated by Django 3.2.10 on 2022-05-23 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220523_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreadcounter',
            name='posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True), size=None),
        ),
    ]
